### ISSUE TITLE
Feature: Reset flag for desired time

### ISSUE THREAD

**Issue by mikekchar** [guyfedwards/omo#1]
I'd like a flag for setting the amount of time desired.  Something like

```
omo reset --min 15
```

Looks pretty easy to implement and I'd be happy to make a PR if you'd like it, but I also don't want to take fun away from your project :-)

**Comment by mrpandey** [comment]
Any update on this?

**Comment by guyfedwards** [comment]
@mikekchar are you still interested in contributing? I haven't had any time to look at this. Also, sorry for not responding, must have missed the notification.

**Comment by MitchellBerend** [comment]
This also seems useful to me, do you mind if I try to implement this?

**Comment by guyfedwards** [comment]
You go for it thanks @MitchellBerend

**Comment by MitchellBerend** [comment]
Okay so I thought the reset timer would function as the new period between notifications. There would need to be some type of persistent storage of the timer length so I was thinking of just adding that to the `/tmp/.omo` file. 

This feature can also be treated as a one time only timer if that is more preferable.
