### ISSUE TITLE
Updating `Clap` to the latest version to add auto completion for bash

### ISSUE THREAD

**Issue by MitchellBerend** [guyfedwards/omo#2]
I always like it when clis have an autocomplete function so I thought I would contribute an auto complete script for this project. [Clap_complete](https://crates.io/crates/clap_complete) only supports Clap versions 3 and 4 though so if this project is accepting prs I have a working version ready for merging.

The about text only mentions bash currently (which works for me) but maybe this should be changed to some generic text. The library supports the following shells: 

[shells::Bash](https://docs.rs/clap_complete/4.3.2/clap_complete/shells/struct.Bash.html)
    [shells::Elvish](https://docs.rs/clap_complete/4.3.2/clap_complete/shells/struct.Elvish.html)
    [shells::Fish](https://docs.rs/clap_complete/4.3.2/clap_complete/shells/struct.Fish.html)
    [shells::PowerShell](https://docs.rs/clap_complete/4.3.2/clap_complete/shells/struct.PowerShell.html)
    [shells::Zsh](https://docs.rs/clap_complete/4.3.2/clap_complete/shells/struct.Zsh.html)

**Comment by guyfedwards** [comment]
Hey thanks for this, I'm happy to review a PR if you have one ready to go, can't see any issue with adding autocomplete if it's minimal.
